### ISSUE TITLE
Selenium-Ruby documentation is out of date

### ISSUE THREAD

**Issue by islemaster** [applitools/eyes.sdk.ruby#28]
The README on this repository says

> Please check the applitools website for usage instructions: http://www.applitools.com

But the [Selenium-Ruby documentation](https://applitools.atlassian.net/wiki/display/Java/Selenium+-+Ruby) on your wiki appears to apply to 2.x versions of the `eyes_selenium` gem.  For example, it still uses `Applitools::Eyes.new` instead of `Applitools::Selenium::Eyes.new`. It also describes setting up a test batch by calling `Applitools::Base::BatchInfo.new` which has [moved to `Applitools::BatchInfo`](https://github.com/applitools/eyes.sdk.ruby/commit/c0c6a264db73ac517182f188feb8ea9632b3403a), and [doesn't show up in the RubyDoc for 3.x versions](http://www.rubydoc.info/gems/eyes_selenium/3.2.1) of the gem, so it's not clear whether it's still considered a public API.

**Comment by danielputerman** [comment]
Hi @islemaster, thanks for the feedback. You're correct, and we will update the Wiki soon, also I'll provide a more accurate link to the new documentation (https://www.applitools.com/resources/tutorial).
