### ISSUE TITLE
eyes_appium interferes with eyes-selenium.

### ISSUE THREAD

**Issue by tanTheta** [applitools/eyes.sdk.ruby#282]
If both the libraries are required in the spec file, eyes_selenium does not work as expected.

https://github.com/applitools/eyes.sdk.ruby/blob/v3.17.22/lib/applitools/selenium/selenium_eyes.rb#L661 returns a true if both libraries are required by the spec.

**Logs (when spec has both eyes_appium and eyes_selenium)**

`I, [2021-03-05T17:33:51.034854 #24526]  INFO --  (70106608766480): "Agent = eyes.selenium.ruby/3.17.22"
I, [2021-03-05T17:33:51.035027 #24526]  INFO --  (70106608766480): "openBase(app_name: Ruby SDK, test_name: Applitools example, viewport_size: 800x600)"
I, [2021-03-05T17:33:51.035093 #24526]  INFO --  (70106608766480): "No running session, calling start session.."
I, [2021-03-05T17:33:51.035164 #24526]  INFO --  (70106608766480): "start_session()"
I, [2021-03-05T17:33:51.035293 #24526]  INFO --  (70106608766480): "EyesTargetLocator.default_content()"
I, [2021-03-05T17:33:51.035365 #24526]  INFO --  (70106608766480): "Set viewport size 800x600"
D, [2021-03-05T17:33:51.035421 #24526] DEBUG --  (70106608766480): "extract_viewport_size()"
D, [2021-03-05T17:33:51.057721 #24526] DEBUG --  (70106608766480): "Viewport size is 1280x784."
I, [2021-03-05T17:33:51.057821 #24526]  INFO --  (70106608766480): "Initial viewport size: 1280x784"
I, [2021-03-05T17:33:51.073070 #24526]  INFO --  (70106608766480): "Current browser size: 1280x858"
I, [2021-03-05T17:33:51.073193 #24526]  INFO --  (70106608766480): "Trying to set browser size to 800x674"
I, [2021-03-05T17:33:52.123797 #24526]  INFO --  (70106608766480): "Current browser size: 800x674"
D, [2021-03-05T17:33:52.123868 #24526] DEBUG --  (70106608766480): "extract_viewport_size()"
D, [2021-03-05T17:33:52.130130 #24526] DEBUG --  (70106608766480): "Viewport size is 800x600."
I, [2021-03-05T17:33:52.130259 #24526]  INFO --  (70106608766480): "EyesTargetLocator.frames(:frame_chain => a_chain) []"
I, [2021-03-05T17:33:52.136072 #24526]  INFO --  (70106608766480): "No OS set, checking for mobile OS..."
I, [2021-03-05T17:33:52.136174 #24526]  INFO --  (70106608766480): "Mobile device detected! Checking device type..."
I, [2021-03-05T17:33:52.136268 #24526]  INFO --  (70106608766480): "Unknown device type"
I, [2021-03-05T17:33:52.136344 #24526]  INFO --  (70106608766480): "Application environment is os: ; hostingApp: ; displaySize: {:width=>800, :height=>600}; inferred: useragent: Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0 CK SEO Team; deviceInfo: Desktop; "

**Logs (when spec has eyes_selenium only)**

`I, [2021-03-05T17:32:59.097845 #24401]  INFO --  (70114393394720): "Agent = eyes.selenium.ruby/3.17.22"
I, [2021-03-05T17:32:59.097949 #24401]  INFO --  (70114393394720): "openBase(app_name: Ruby SDK, test_name: Applitools example, viewport_size: 800x600)"
I, [2021-03-05T17:32:59.098144 #24401]  INFO --  (70114393394720): "No running session, calling start session.."
I, [2021-03-05T17:32:59.098190 #24401]  INFO --  (70114393394720): "start_session()"
I, [2021-03-05T17:32:59.098324 #24401]  INFO --  (70114393394720): "EyesTargetLocator.default_content()"
I, [2021-03-05T17:32:59.098433 #24401]  INFO --  (70114393394720): "Set viewport size 800x600"
D, [2021-03-05T17:32:59.098527 #24401] DEBUG --  (70114393394720): "extract_viewport_size()"
D, [2021-03-05T17:32:59.172766 #24401] DEBUG --  (70114393394720): "Viewport size is 1280x784."
I, [2021-03-05T17:32:59.172859 #24401]  INFO --  (70114393394720): "Initial viewport size: 1280x784"
I, [2021-03-05T17:32:59.198049 #24401]  INFO --  (70114393394720): "Current browser size: 1280x858"
I, [2021-03-05T17:32:59.198305 #24401]  INFO --  (70114393394720): "Trying to set browser size to 800x674"
I, [2021-03-05T17:33:00.288974 #24401]  INFO --  (70114393394720): "Current browser size: 800x674"
D, [2021-03-05T17:33:00.289058 #24401] DEBUG --  (70114393394720): "extract_viewport_size()"
D, [2021-03-05T17:33:00.294658 #24401] DEBUG --  (70114393394720): "Viewport size is 800x600."
I, [2021-03-05T17:33:00.294752 #24401]  INFO --  (70114393394720): "EyesTargetLocator.frames(:frame_chain => a_chain) []"
I, [2021-03-05T17:33:00.301160 #24401]  INFO --  (70114393394720): "No OS set, checking for mobile OS..."
I, [2021-03-05T17:33:00.301319 #24401]  INFO --  (70114393394720): "Application environment is os: ; hostingApp: ; displaySize: {:width=>800, :height=>600}; inferred: useragent: Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0 CK SEO Team; deviceInfo: Desktop; "
`

**Comment by danielputerman** [comment]
@tanTheta Thank you for notifying us. 
Please open a request for support [at] applitools.com, so we can track this issue and notify you accordingly.
