### ISSUE TITLE
eyes_base.rb : in case of failures, '.' is appended to the results_url. 

### ISSUE THREAD

**Issue by tanTheta** [applitools/eyes.sdk.ruby#80]
eyes_base.rb : in case of failures, '.' is appended to the results_url. 
As a result, when user clicks on the URL (which is technically an invalid URL), he gets an access denied screen.

In order to proceed, user needs to manually remove the '.' from URL.

**Comment by danielputerman** [comment]
Fixed in 0948906c045a7bb188c09ad624b617460176c087 and available in version 3.13.0.

Thanks!
